/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @format
 */

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};


/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'introduction',
    {
      type: 'category',
      label: '简介',
      items: [
        {
          type: 'autogenerated',
          dirName: 'introduction',
        },
      ],
    },
    {
      type: 'category',
      label: '快速开始',
      link: {
        type: 'generated-index',
      },
      items: [
        'getting-started/start-project',
        {
          type: 'category',
          label: 'Server 部署指南',
          link: {
            type:'generated-index',
            },
          items: [
            {
              type: 'autogenerated',
              dirName: 'getting-started/server',
            },
          ],
        },
        {
          type: 'category',
          label: 'Agent 安装指南',
          link: {
            type:'generated-index',
            },
          items: [
            {
              type: 'autogenerated',
              dirName: 'getting-started/agent',
            },
          ],
        },
        'getting-started/start-xjpc',     
      ],      
    },
    {
      type: 'category',
      label: '操作手册',
      link: {
        type: 'generated-index',
      },  
      items: [
        {
          type: 'autogenerated',
          dirName: 'operation',
        },
      ],
    }, 
    {
      type: 'category',
      label: '教学指南',
      link: {
        type: 'generated-index',
      },       
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial',
        },        
      ],
    },
    {
      type: 'category',
      label: '实践案例',
      link: {
        type: 'generated-index',
      },     
      items: [
        'best-practice-case',
        {
          type: 'category',
          label: '持续集成',
          link: {
            type:'generated-index',
            },
          items: [
            {
              type: 'autogenerated',
              dirName: 'integration',
            },
          ],
        },        
      ],
    },    
    {
      type: 'category',
      label: '性能测试',
      items: [
        {
          type: 'autogenerated',
          dirName: 'testing-report',
        },
      ],
    },
    {
      type: 'category',
      label: '常见问题',
      link: {
        type: 'generated-index',
      },       
      items: [
        {
          type: 'autogenerated',
          dirName: 'get-help',
        },        
      ],
    },
    'user-case',    
    'resource-case',
  ],
  api: [
    {
      type: 'autogenerated',
      dirName: 'api',
    },         
  ],  
  development: [
    {
      type: 'autogenerated',
      dirName: 'development',
    },
  ],
  changelog: [
    {
      type: 'autogenerated',
      dirName: 'changelog',
    },
  ],
};

module.exports = sidebars;
