/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @format
 */

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};


/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'introduction',
    {
      type: 'category',
      label: '简介',
      items: [
        {
          type: 'autogenerated',
          dirName: 'introduction',
        },
      ],
    },
    {
      type: 'category',
      label: '快速开始',
      link: {
        type: 'generated-index',
        keywords: ['安装指南'],
      },      
      items: [
        {
          type: 'autogenerated',
          dirName: 'getting-started',
        },
      ],
    },
    {
      type: 'category',
      label: '操作手册',
      items: [
        {
          type: 'autogenerated',
          dirName: 'operation',
        },
      ],
    }, 
    {
      type: 'category',
      label: '实践教学',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial',
        },
      ],
    },
    'best-practice-case',
    {
      type: 'category',
      label: '性能测试',
      items: [
        {
          type: 'autogenerated',
          dirName: 'testing-report',
        },
      ],
    },
    {
      type: 'category',
      label: '常见问题',
      link: {
        type: 'generated-index',
      },       
      items: [
        {
          type: 'autogenerated',
          dirName: 'get-help',
        },        
      ],
    },
    'resource-case',
  ],
  api: [
    {
      type: 'autogenerated',
      dirName: 'api',
    },         
  ],  
  changelog: [
    {
      type: 'autogenerated',
      dirName: 'changelog',
    },
  ],
};

module.exports = sidebars;
